x = input('digite algo:')
print('o tipo primitivo desse texto é:', type(x))
print('esse texto é um número e/ou número?', x.isalnum())
print('esse texto é uma letra do alfabeto?', x.isalpha())
print('está em minúsculo?', x.islower())
print('tem número?', x.isnumeric())
print('tem espaço?', x.isspace())
print('está capitalizada?', x.istitle())
print('está em maiúculo?', x.isupper())